marcas/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import listadomarca, nuevamarca, editarmarca

urlpatterns = [
    path('listado/', listadomarca, name='listadomarca'),
    path('nuevo/', nuevamarca, name='nuevamarca'),
    path('editar/<int:pk>', editarmarca, name='editarmarca'),
]

articulos/models.py
from datetime import datetime

from django.db import models
from marcas.models import Marca
from proveedores.models import Proveedor


class Articulo(models.Model):
    codigoaccess = models.CharField(max_length=50, null=True, blank=True) 
    descripcion = models.CharField(max_length=250, null=False, blank=False)
    minimo = models.IntegerField(null=True, blank=True)
    iva = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE, null=True, blank=True)
    grupo = models.IntegerField(null=True, blank=True)
    pventa1 = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    pventa2 = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    pventa3 = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    pventa4 = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    comib = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    comiu = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    codigobarra = models.CharField(max_length=250, null=True, blank=True)
    pmoneda = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    cotizacion = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    pcompra = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    ocultar = models.BooleanField(default=False, null=True, blank=True)
    margen1 = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    margen2 = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    margen3 = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    margen4 = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    d1 = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    d2 = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    d3 = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    flete = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    fechaprecio = models.DateTimeField(null=True, blank=True)
    codigoproducto = models.CharField(max_length=250, null=True, blank=True)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE, null=True, blank=True)
    selecciones = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return self.descripcion.upper()
    
    def save(self, *args, **kwargs):
        self.descripcion = self.descripcion.upper()
        ahora = datetime.now()
        self.fechaprecio=ahora
        super(Articulo, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Articulos"




# Create your models here.

templates/base_empty.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Mantenimiento y Construcciones SRL </title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css'%}">
  <!-- Ionicons -->
  <!--link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"-->
  <link rel="stylesheet" href="{% static 'dist/css/ionicons.min.css'%}">
  
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css'%}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css'%}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'%}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css'%}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css'%}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.css'%}">
  <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">

  <!-- Datepicker -->
  <link rel="stylesheet" href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}">

  <!-- Tempus-Dominus Bootstrp 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'%}">

</head>


{%block content %}

{% endblock %}


{% block js_extra %}
{% endblock %}
</html>

templates/base_nomenu.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Mantenimiento y Construcciones SRL </title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css'%}">
  <!-- Ionicons -->
  <!--link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"-->
  <link rel="stylesheet" href="{% static 'dist/css/ionicons.min.css'%}">
  
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css'%}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css'%}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'%}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css'%}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css'%}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.css'%}">
  <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">

  <!-- Datepicker -->
  <link rel="stylesheet" href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}">

  <!-- Tempus-Dominus Bootstrp 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'%}">

</head>

<header class="onlyprint">
  <img style="float: right;" src="{% static "images/logo.jpg" %}" alt="" width="112" height="69">
</header>


<style>
  @media print{
    @page {
      size: landscape; 
    }
    
    header {
      position: static; /* Esto asegura que el header no se quede fijo al imprimir */
      top: 0;
      z-index: 1000;
      background-color: #fff;
      opacity: 0.7; /* Para que no tape el texto */
      
    }

    footer {page-break-after: always;}
  }

  header {
        position: fixed;
        top: 0;
        right: 0; /* Ajusta la posición a la derecha */
        /* otros estilos para el encabezado */
        opacity: 0.7; /* Para que no tape el texto */
  }

  
  table {
    border-collapse: collapse;
    width: 100%;
    border: 1px solid #ddd;
    font-size: 12px;
  }
  
  th, td {
    text-align: left;
    padding: 1px;
    font-size: 12px;
  }
  
  .fecha {
    font-size: 12px;
  }

  .nombreobra {
    font-size: 14px;
  }
</style>
<body>

{%block content %}

{% endblock %}

</body>

{% block js_extra %}
{% endblock %}

<footer>
  
</footer>

</html>

templates/base_nomenu_bck.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Mantenimiento y Construcciones SRL </title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css'%}">
  <!-- Ionicons -->
  <!--link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"-->
  <link rel="stylesheet" href="{% static 'dist/css/ionicons.min.css'%}">
  
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css'%}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css'%}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'%}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css'%}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css'%}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.css'%}">
  <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">
  
  <!-- Full Calendar -->
  <link rel="stylesheet" href="{% static 'plugins/fullcalendar/main.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/fullcalendar-daygrid/main.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/fullcalendar-timegrid/main.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/fullcalendar-bootstrap/main.min.css' %}">

  <!-- Datepicker -->
  <link rel="stylesheet" href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}">

  <!-- Tempus-Dominus Bootstrp 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'%}">

</head>

<header>
  <img style="float: right;" src="{% static "images/logo.jpg" %}" alt="" width="150" height="93">
</header>

<body>
<div class="wrapper">

  <!-- Content Wrapper. Contains page content -->
  <div>
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
              <!--a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a-->
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!--a class="breadcrumb-item" href="/salir">Salir</a-->
            </ol>
          </div>
        </div>
      </div>
    </div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          {%block content %}
          {% endblock %}
        </div>
      </div>
    </section>
  </div>

  <!--footer class="main-footer">
    <strong>Copyright &copy; 2023 </strong>
    Todos los Derechos Reservados.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0.0
    </div>
  </footer-->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js'%}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js'%}"></script>

<!-- FLOT CHARTS -->
<script src="{% static 'plugins/flot/jquery.flot.js'%}"></script>
<!--script src="../../plugins/flot/jquery.flot.js"></script-->


<!-- fullCalendar 2.2.5 -->
<script src="{% static 'plugins/fullcalendar/main.min.js'%}"></script>
<script src="{% static 'plugins/fullcalendar-daygrid/main.min.js'%}"></script>
<script src="{% static 'plugins/fullcalendar-timegrid/main.min.js'%}"></script>
<script src="{% static 'plugins/fullcalendar-interaction/main.min.js'%}"></script>
<script src="{% static 'plugins/fullcalendar-bootstrap/main.min.js'%}"></script>
<script src="{% static 'plugins/fullcalendar/locales/es.js'%}"></script>


<!-- Sparkline -->
<script src="{% static 'plugins/sparklines/sparkline.js'%}"></script>
<!-- JQVMap -->
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js'%}"></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js'%}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/jquery-knob/jquery.knob.min.js'%}"></script>
<!-- daterangepicker -->
<script src="{% static 'plugins/moment/moment.min.js'%}"></script>
<!--script src="{% static 'plugins/moment/moment-with-locales.min.js'%}"></script-->
<script src="{% static 'plugins/moment/locale/es.js'%}"></script>

<script src="{% static 'plugins/daterangepicker/daterangepicker.js'%}"></script>

<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js'%}"></script>
<!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js'%}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js'%}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js'%}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<!--script src="{% static 'dist/js/pages/dashboard.js'%}"></!--script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'plugins/select2/js/select2.full.min.js'%}"></script>
<script src="{% static 'dist/js/demo.js'%}"></script>


<!-- Datepicker -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.js'%}"></script>

</body>

{% block js_extra %}
{% endblock %}
</html>

templates/base_nomenu_bckk.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Mantenimiento y Construcciones SRL </title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css'%}">
  <!-- Ionicons -->
  <!--link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"-->
  <link rel="stylesheet" href="{% static 'dist/css/ionicons.min.css'%}">
  
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css'%}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css'%}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'%}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css'%}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css'%}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.css'%}">
  <link rel="stylesheet" href="{% static 'plugins/select2/css/select2.min.css'%}">
  
  <!-- Full Calendar -->
  <link rel="stylesheet" href="{% static 'plugins/fullcalendar/main.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/fullcalendar-daygrid/main.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/fullcalendar-timegrid/main.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/fullcalendar-bootstrap/main.min.css' %}">

  <!-- Datepicker -->
  <link rel="stylesheet" href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}">

  <!-- Tempus-Dominus Bootstrp 4 -->
  <link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css'%}">

</head>

<header>
  <img style="float: right;" src="{% static "images/logo.jpg" %}" alt="" width="150" height="93">
</header>

<body>
<div class="wrapper">

  <!-- Content Wrapper. Contains page content -->
  <div>
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
              <!--a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a-->
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!--a class="breadcrumb-item" href="/salir">Salir</a-->
            </ol>
          </div>
        </div>
      </div>
    </div>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        
          {%block content %}
          {% endblock %}
        
      </div>
    </section>
  </div>

  <!--footer class="main-footer">
    <strong>Copyright &copy; 2023 </strong>
    Todos los Derechos Reservados.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0.0
    </div>
  </footer-->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js'%}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js'%}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js'%}"></script>

<!-- FLOT CHARTS -->
<script src="{% static 'plugins/flot/jquery.flot.js'%}"></script>
<!--script src="../../plugins/flot/jquery.flot.js"></script-->


<!-- fullCalendar 2.2.5 -->
<script src="{% static 'plugins/fullcalendar/main.min.js'%}"></script>
<script src="{% static 'plugins/fullcalendar-daygrid/main.min.js'%}"></script>
<script src="{% static 'plugins/fullcalendar-timegrid/main.min.js'%}"></script>
<script src="{% static 'plugins/fullcalendar-interaction/main.min.js'%}"></script>
<script src="{% static 'plugins/fullcalendar-bootstrap/main.min.js'%}"></script>
<script src="{% static 'plugins/fullcalendar/locales/es.js'%}"></script>


<!-- Sparkline -->
<script src="{% static 'plugins/sparklines/sparkline.js'%}"></script>
<!-- JQVMap -->
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js'%}"></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js'%}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/jquery-knob/jquery.knob.min.js'%}"></script>
<!-- daterangepicker -->
<script src="{% static 'plugins/moment/moment.min.js'%}"></script>
<!--script src="{% static 'plugins/moment/moment-with-locales.min.js'%}"></script-->
<script src="{% static 'plugins/moment/locale/es.js'%}"></script>

<script src="{% static 'plugins/daterangepicker/daterangepicker.js'%}"></script>

<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js'%}"></script>
<!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js'%}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js'%}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js'%}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<!--script src="{% static 'dist/js/pages/dashboard.js'%}"></!--script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'plugins/select2/js/select2.full.min.js'%}"></script>
<script src="{% static 'dist/js/demo.js'%}"></script>


<!-- Datepicker -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.js'%}"></script>

</body>

{% block js_extra %}
{% endblock %}
</html>

templates/reporte.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">

        <br>
        
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <h3> Reportes de Factura Individual. </h3>
            </div>
            <div class="col-sm-2"></div>
        </div>

        <hr>

        <form action="/reportes/" method="GET">
            <div class="form-inline">
                <div class="col-6">
                    <label>Proveedores</label>
                    <select id="id_proveedor" class="form-control">
                        <option value="0"> ------------- </option>
                        {% for proveedor in proveedores %}
                            <option value={{proveedor.pk}}> {{proveedor.proveedor }} - {{proveedor.comprobante}} </option>
                        {% endfor %}
                    </select>
                </div>

                <div class="col-6">
                    <label>Banco</label>
                    <select id="id_banco" class="form-control">
                    </select>
                </div>
                
            </div>


            <div class="form-inline">
                <div class="col-6">
                    <label for="id_fechadesde">Fecha Desde:</label> 
                    <input type="text" name="id_fechadesde" class="form-control" required id="id_fechadesde">
                </div>

                <div class="col-6">
                    <label for="id_fechahasta">Fecha Hasta:</label> 
                    <input type="text" name="id_fechahasta" class="form-control" required id="id_fechahasta">
                </div>
            </div>

            <hr>

            <div class="form-inline">
                <div class="col-6">
                </div>
            </div>

            <div class="form-inline">
                <div class="col-4">
                </div>

                <div class="col-4">
                    <button type="button" class="btn btn-default" title="Generar" onclick="AbrirVentanaReporte()">
                        <i class="fas fa-play"></i>
                    </button>
                </div>

                <div class="col-4">
                </div>
            </div>

            <br>

        </form>
    </div>

{% endblock %}


{% block js_extra %}

    <script>
        $(document).ready(function () {
            $('#id_proveedor').select2();
            TranslateDatepickerToEs($("#id_fechadesde"));
            TranslateDatepickerToEs($("#id_fechahasta"));
        });


        $("#id_proveedor").on('change', function(e) {
            var idproveedor = $(this).select2('data')[0].id;
            //CargarCombo($(this).select2('data')[0].id);
            CargarCombo(idproveedor);
        });


        function CargarCombo(id){
            $.ajax({
                type: "GET",
                url: "/ajaxbancoproveedor/" + id,
                dataType: "json",
                success: function (response) {
                    var select = $('#id_banco');
                    select.empty();

                    $.each(response, function(index, value) {
                    select.append($('<option>', {
                        value: value.id,
                        text: value.text
                    }));
            });
                }
            });
        }

        function AbrirVentanaReporte(){
            var id_proveedor = $("#id_proveedor").val();
            var id_banco = $("#id_banco").val();
            var id_fechadesde = $("#id_fechadesde").val();
            var id_fechahasta = $("#id_fechahasta").val();

            if(id_banco==0 || id_banco==null){
                Swal.fire(
                    'Por favor elige un Banco',
                    '',
                    'warning'
                )
                return false;
            }
            
            var urldetallefactura = "/detallereporte/?id_proveedor=" + id_proveedor + "&id_banco=" + id_banco + "&id_fechadesde=" + id_fechadesde + "&id_fechahasta=" + id_fechahasta ;
            window.open(urldetallefactura,"Ratting","width=750,height=650,left=100,top=100,toolbar=0,status=0,");
        }



    
    </script>

{% endblock %}